### ISSUE TITLE
editar textos

### ISSUE THREAD

**Issue by monteirocamis** [Codivas/landing-codivas-V1#11]
- substitui textos por informações do coletivo como :

-  "camis monteiro" por "coletivo codivas"
- "Desenvolvedora web e IoT" por "Somos um coletivo de mulheres em tecnologia " 
-   "Freelancer em Full-stack, Android e Iot!" por "Desenvolvimento web, Android  e IoT" 
-  "Experiência com sites institucionais, e-commerces e wearables(fashion tech)" por "Somos um coletivo de profissionais Freelancers para criação ou manutenção de sites, aplicativos e internet das coisas. Temos experiência com diversas linguagens de programação e plataformas do mercado."
- "Modelagem digital para web e impressão 3D"  por "Esteja pronto para atender o mercado digital !"
-  "Fale comigo!" por "Fale conosco"
-"Entre em contato que retornarei o quanto antes! "por "Entre em contato que retornaremos o quanto antes!

**Comment by natayra** [comment]
I can do this one

**Comment by monteirocamis** [comment]
mana se voce ainda estiver disponivel , esqueci de trocar o email tambem.. coletivocodivas@gmail.com

**Comment by natayra** [comment]
> mana @natayra se voce ainda estiver disponivel , esqueci de trocar o email tambem.. [coletivocodivas@gmail.com](mailto:coletivocodivas@gmail.com)

**Comment by natayra** [comment]
Done
