### ISSUE TITLE
translate - portugues para inglês 

### ISSUE THREAD

**Issue by monteirocamis** [Codivas/landing-codivas-V1#13]
editar as issues e read-me em inglês, para poder participar do hacktoberfest

**Comment by natayra** [comment]
Para o repositório fazer parte do Hacktoberfest o tópico "hacktoberfest" tem de ser adicionado.  Se ainda for preciso ajuda eu posso contribuir e traduzir os issues tal como o Readme

**Comment by monteirocamis** [comment]
oioi @natayra  quero sim  por favor!! ;)

**Comment by monteirocamis** [comment]
@natayra eu inseri a issue hacktoberfest ... será que agora vai ? hehe muito obrigada pela dica!!

**Comment by kleyla** [comment]
I'd love to work on this @monteirocamis

**Comment by monteirocamis** [comment]
@kleyla  please send your PR =))
