### ISSUE TITLE
hacktoberfest

### ISSUE THREAD

**Issue by monteirocamis** [Codivas/landing-codivas-V1#14]
Bora ajudar a colocar nossa landing no ar? 
esse codigo seria pra ficar parecido com a minha pagina de portfolio por exemplo https://monteirocamis.github.io/

**Comment by rdr42** [comment]
Oi @monteirocamis , você pode assinar esse issue pra mim?

**Comment by kleyla** [comment]
I would like to help you, I am learning portuguese

**Comment by monteirocamis** [comment]
@rdr42  opa!! claro.. tudo pronto aqui pra receber ;)

**Comment by monteirocamis** [comment]
@kleyla  sure! but  I think @rdr42 will make it , but please send your pr's here ou in other issues =)

**Comment by monteirocamis** [comment]
gente to um pouco perdida com esse novo padrão do hacktoberfest esse ano, se precisar arrumar algo me avisem por favor !!
obrigada  =)

Hey friends, I am a little lost with this new way of hacktoberfest this year..so please let me know If I have to make some changes here or in any issue !!
thank you !!

**Comment by kleyla** [comment]
@monteirocamis  Classifying a repository as ‘hacktoberfest’ eligible
![hacktoberfest-eligible-gif](https://user-images.githubusercontent.com/39011391/97094306-e06e7800-1621-11eb-849f-2b9718b40174.gif)

https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by monteirocamis** [comment]
@kleyla oh thank you !! I was looking for this video, now I think it's working =)
