### ISSUE TITLE
create contributing.id

### ISSUE THREAD

**Issue by monteirocamis** [Codivas/landing-codivas-V1#16]

**Comment by monteirocamis** [comment]
#### Name: [CAMILA MONTEIRO](https://github.com/monteirocamis)
- Place:  São Paulo, Brazil
- Bio:  Front-End , IoT and Android Developer.

### Development

- Web development (HTML,CSS,JavaScript,C++,Bootstrap,React, PHP,Android,mySQL)
- Internet of things & Wearables (C++,Arduino, NodeMCU)

### Projects

- TrocaTex - OpenSource - Exchange of leftovers of textiles (https://github.com/monteirocamis/trocatexproject)
- Codivas -  cowork - OpenSource - (https://github.com/codivas)
- Camon - Brand - Clothes made with sustainable design and wearable projects(https://www.ateliecamon.com.br)







#### Name: [YOUR NAME ](https://github.com/yourgithubprofile)
- Place: city, country 
- Bio: Full stack? Web designer? Programmer ...Put everything here


### Development

- What languages do you use?
- what else you know?

### Projects

- name  - OpenSource ? - infos  (https://github.com/yourprojectlink)
- name - what you do? (https://www.yourprojectlink.com)

- Website: [your website](https://www.yourwebsite.com)

**Comment by kleyla** [comment]
I would like to work in it.. :)

**Comment by monteirocamis** [comment]
@kleyla please join us !! send you PR with this issue
