### ISSUE TITLE
trocar favicon / change favicon

### ISSUE THREAD

**Issue by monteirocamis** [Codivas/landing-codivas-V1#24]
trocar o nome "camis dev"da aba pelo logo do coletivo em favicon

change the "camis dev" to logo from codivas in favicon .
![logo codivas 2 - transp](https://user-images.githubusercontent.com/26682838/97121582-200a9200-16fe-11eb-89f1-9f03f29b866b.png)

![logo codivas - transp](https://user-images.githubusercontent.com/26682838/97121581-1f71fb80-16fe-11eb-825e-7e12028d4ae4.png)

**Comment by natayra** [comment]
Alterei o Favicon para o logo na horizontal
