### ISSUE TITLE
inserir secao de agencias parceiras // include partners section

### ISSUE THREAD

**Issue by monteirocamis** [Codivas/landing-codivas-V1#41]
precisamos criar uma nossa secao antes de contato, com as agencias parceiras.
Colocando o logo das agencias. 
Voce pode pegar o codigo do tema agency, do start boostrap https://startbootstrap.com/previews/agency/

we need to inclue partners section, with the logo and url.
You can get this part of code from agency theme, from start bootstrap https://startbootstrap.com/previews/agency/

![image](https://user-images.githubusercontent.com/26682838/97791736-66576980-1bb4-11eb-8c3c-1cd0a96da6d4.png)

**Comment by monteirocamis** [comment]
logos até o momento:
![umbler-logo-light-bg](https://user-images.githubusercontent.com/26682838/97791854-af5bed80-1bb5-11eb-9ac5-aa5e1baad4f0.png)

**Comment by kleyla** [comment]
@monteirocamis  I would like to work on it

**Comment by monteirocamis** [comment]
heey @kleyla , please send us your PR =)

**Comment by monteirocamis** [comment]
nós temos mais 1 logo pra inserir e trocar o logo do RBW
we have 1 more logo to include and also change the RBW logo

![Logo_rbw_reduzido-01](https://user-images.githubusercontent.com/26682838/98065471-76c94780-1e33-11eb-83cc-4ce5b0401634.png)
![Prancheta 1](https://user-images.githubusercontent.com/26682838/98065476-78930b00-1e33-11eb-9a02-5bfad00d61c9.png)

**Comment by kleyla** [comment]
I will change and add them
