### ISSUE TITLE
mudar serviços / change services

### ISSUE THREAD

**Issue by monteirocamis** [Codivas/landing-codivas-V1#60]
mudar os itens de serviços para :
internet das coisas para midias sociais: conteúdos, anúncios e  integração com e-mail marketing e analytics.

![image](https://user-images.githubusercontent.com/26682838/99456655-7f784e00-2908-11eb-8b40-a5d6bc5ddbaa.png)

**Comment by natayra** [comment]
@monteirocamis aqui é para alterar o terceiro Serviço (que neste momento tem "Internet das coisas" para Midias Sociais? 
E a descrição por baixo em vez do que está agora, passa a "Conteúdos, , anúncios e integração com e-mail marketing e analytics"?

**Comment by monteirocamis** [comment]
oiii  isso! vou pensar algo para colocar embaixo de midias sim

**Comment by natayra** [comment]
Fiz um Pull Request, vê lá se é isso

**Comment by monteirocamis** [comment]
Nat a gente mudou de ideia aqui, eu e a Fernanda que é a de midias sociais hehe Pensamos em incluir um novo icone com midias sociais sem deletar o de Iot , e também incluir um outro de Data analytics .
seria 
Midias sociais - Design de conteúdos, Ads  e integrações.
Data analytics - SEO, Google e análises de dados.
