### ISSUE TITLE
foto banner

### ISSUE THREAD

**Issue by monteirocamis** [Codivas/landing-codivas-V1#9]
trocar a foto do computador e cadeira por alguma que represente melhor o coletivo.
podemos buscar em sites de imagens gratuitas

**Comment by natayra** [comment]
Que tipo de imagem? Pode dar um exemplo de algo que represente melhor o coletivo?

**Comment by monteirocamis** [comment]
siim... algo que tenha mulher desenvolvedora, home office com mulher, time de mulheres ..

**Comment by natayra** [comment]
Tenho algumas ideias para esta alteração. Tentei que não fosse muito cliché e gostaria da sua opinião @monteirocamis 

Depois diz se alguma é do seu agrado para eu fazer um PR

1.  
![image](https://user-images.githubusercontent.com/38838615/97183428-1173b780-179e-11eb-8f0b-0270d5d6f0c5.png)

2.
![image](https://user-images.githubusercontent.com/38838615/97183658-54ce2600-179e-11eb-9171-3fd3d46bea6d.png)

3.
![image](https://user-images.githubusercontent.com/38838615/97183752-7202f480-179e-11eb-8fb5-061ef81630af.png)

4.
![image](https://user-images.githubusercontent.com/38838615/97183849-88a94b80-179e-11eb-9452-9deb2ace6e73.png)

**Comment by monteirocamis** [comment]
ameeei a ultima !!! pode por ela... mas se puder colocar todas as imagens dentro da pasta de imagens já e ai depois com tempo  podemos implementar o carosel com elas e varias chamadas diferentes o que acha?

**Comment by natayra** [comment]
Combinado. Vou fazer isso hoje e depois mando o PR (a última também é a minha preferida 😊)

**Comment by monteirocamis** [comment]
Se você tiver interesse de participar do nosso grupo de whatsapp ou no telegram me chama no insta @coletivo.codivas . Lá compartilhamos as oportunidades de freelas compartilhados e montamos os times para atender o mercado =)
